#!/bin/bash
#SBATCH --job-name="Kallisto_cDNA"
#SBATCH --time=4:00:00 
#SBATCH -n 1
#SBATCH -N 1
#SBATCH --cpus-per-task 16
#SBATCH --mail-user=${USER}@tgen.org

cd $DIR

# Load kallisto module
#module load kallisto/0.42.4
#module load salmon/0.5.0


#####################################################
##
##   VARIABLES
##
#####################################################

#KALLISTO_BINARY=/home/clegendre/tools/kallisto/0.42.4/bin/kallisto
KALLISTO_BINARY=/home/achristofferson/local/kallisto_linux-v0.42.4/kallisto
KALLISTO_INDEX_cDNA=/home/achristofferson/kallisto_index/Homo_sapiens.GRCh37.74.cdna.hs37d5.fasta.index

# Make fastq list for Kallisto
FASTQS="`ls -1 ${SAMPLE}*.fastq.gz | tr '\n' ' '`"

${KALLISTO_BINARY} quant \
        -i ${KALLISTO_INDEX_cDNA} \
        -t 14 \
        -b 100 \
        -o ${SAMPLE}.kallistoDir/ensembl74_cDNA \
        ${FASTQS}

if [ "$?" -ne "0" ]
then
	ssh ${USER}@10.48.73.17 "cd ${STARTDIR}/${PATIENT_NAME} ; \
		rm ${ASSAY}/${RNASAMPLEID}/${RNASAMPLEID}.kallistoDir/ensembl74_cDNA/Kallisto_In_Progress ; \
		echo Kallisto failed for ${RNASAMPLEID} >> ${ASSAY}/${RNASAMPLEID}/${RNASAMPLEID}.kallistoDir/ensembl74_cDNA/Kallisto_Fail ; \
		echo Kallisto failed for ${RNASAMPLEID} | mailx -s "Post Medusa Processing Failed" ${USER}@tgen.org"
	exit 1
else
	cd ${SAMPLE}.kallistoDir/ensembl74_cDNA
	mv abundance.h5 ${SAMPLE}_kallisto_e74cDNA_abundance.h5
	mv abundance.tsv ${SAMPLE}_kallisto_e74cDNA_abundance.tsv

	DIR=`pwd`

	ssh ${USER}@10.48.73.17 "rsync -r ${DIR} ${STARTDIR}/${PATIENT_NAME}/${ASSAY}/${RNASAMPLEID}/${RNASAMPLEID}.kallistoDir/ "

        if [ $? -ne 0 ]
        then
                ssh ${USER}@10.48.73.17 "rm ${STARTDIR}/${PATIENT_NAME}/${ASSAY}/${RNASAMPLEID}/${RNASAMPLEID}.kallistoDir/ensembl74_cDNA/Kallisto_In_Progress ; \
                        echo Failed to rsync kallisto dir to isilon for ${RNASAMPLEID} >> ${STARTDIR}/${PATIENT_NAME}/${ASSAY}/${RNASAMPLEID}/${RNASAMPLEID}.kallistoDir/ensembl74_cDNA/Kallisto_Fail ; \
                        echo Failed to rsync kallisto dir to isilon for ${RNASAMPLEID} | mailx -s "Post Medusa Processing Failed" ${USER}@tgen.org"

        else
                ssh ${USER}@10.48.73.17 "rm ${STARTDIR}/${PATIENT_NAME}/${ASSAY}/${RNASAMPLEID}/${RNASAMPLEID}.kallistoDir/ensembl74_cDNA/Kallisto_In_Progress ; \
                        touch ${STARTDIR}/${PATIENT_NAME}/${ASSAY}/${RNASAMPLEID}/${RNASAMPLEID}.kallistoDir/ensembl74_cDNA/Kallisto_Complete ; \
                        COMPLETE=0 ; \
                        for RSAMPLE in \`echo ${RNACHECK} |sed 's/@/\n/g'\`
                        do
				echo ${STARTDIR}/${PATIENT_NAME}/\${RSAMPLE}.kallistoDir/ensembl74_cDNA/Kallisto_Complete 
                                if [ ! -f ${STARTDIR}/${PATIENT_NAME}/\${RSAMPLE}.kallistoDir/ensembl74_cDNA/Kallisto_Complete ] || [ ! -f ${STARTDIR}/${PATIENT_NAME}/\${RSAMPLE}.kallistoDir/ensembl74_GTF/Kallisto_Complete ]
                                then
                                        COMPLETE=1
                                fi
                        done ; \
                        if [ \${COMPLETE} = 0 ]
                        then
                                rm ${STARTDIR}/${PATIENT_NAME}/Kallisto_In_Progress
                                touch ${STARTDIR}/${PATIENT_NAME}/Kallisto_Complete
                        fi "



        fi
fi


